//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TwitterOnVaadinModel", "FK_BlockedList_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBaseAgent.User), "BlockedList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBaseAgent.BlockedList), true)]
[assembly: EdmRelationshipAttribute("TwitterOnVaadinModel", "FK_BlockedList_User1", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBaseAgent.User), "BlockedList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBaseAgent.BlockedList), true)]
[assembly: EdmRelationshipAttribute("TwitterOnVaadinModel", "FK_FriendList_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBaseAgent.User), "FriendList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBaseAgent.FriendList), true)]
[assembly: EdmRelationshipAttribute("TwitterOnVaadinModel", "FK_FriendList_User1", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBaseAgent.User), "FriendList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBaseAgent.FriendList), true)]
[assembly: EdmRelationshipAttribute("TwitterOnVaadinModel", "FK_Post_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBaseAgent.User), "Post", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBaseAgent.Post), true)]
[assembly: EdmRelationshipAttribute("TwitterOnVaadinModel", "FK_Post_User1", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBaseAgent.User), "Post", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBaseAgent.Post), true)]

#endregion

namespace DBaseAgent
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TwitterOnVaadinEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TwitterOnVaadinEntities object using the connection string found in the 'TwitterOnVaadinEntities' section of the application configuration file.
        /// </summary>
        public TwitterOnVaadinEntities() : base("name=TwitterOnVaadinEntities", "TwitterOnVaadinEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TwitterOnVaadinEntities object.
        /// </summary>
        public TwitterOnVaadinEntities(string connectionString) : base(connectionString, "TwitterOnVaadinEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TwitterOnVaadinEntities object.
        /// </summary>
        public TwitterOnVaadinEntities(EntityConnection connection) : base(connection, "TwitterOnVaadinEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BlockedList> BlockedLists
        {
            get
            {
                if ((_BlockedLists == null))
                {
                    _BlockedLists = base.CreateObjectSet<BlockedList>("BlockedLists");
                }
                return _BlockedLists;
            }
        }
        private ObjectSet<BlockedList> _BlockedLists;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FriendList> FriendLists
        {
            get
            {
                if ((_FriendLists == null))
                {
                    _FriendLists = base.CreateObjectSet<FriendList>("FriendLists");
                }
                return _FriendLists;
            }
        }
        private ObjectSet<FriendList> _FriendLists;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Post> Posts
        {
            get
            {
                if ((_Posts == null))
                {
                    _Posts = base.CreateObjectSet<Post>("Posts");
                }
                return _Posts;
            }
        }
        private ObjectSet<Post> _Posts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BlockedLists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlockedLists(BlockedList blockedList)
        {
            base.AddObject("BlockedLists", blockedList);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FriendLists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFriendLists(FriendList friendList)
        {
            base.AddObject("FriendLists", friendList);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Posts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPosts(Post post)
        {
            base.AddObject("Posts", post);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TwitterOnVaadinModel", Name="BlockedList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlockedList : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BlockedList object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="blockedUser">Initial value of the BlockedUser property.</param>
        public static BlockedList CreateBlockedList(global::System.Int32 id, global::System.Int32 user, global::System.Int32 blockedUser)
        {
            BlockedList blockedList = new BlockedList();
            blockedList.id = id;
            blockedList.User = user;
            blockedList.BlockedUser = blockedUser;
            return blockedList;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.Int32 _User;
        partial void OnUserChanging(global::System.Int32 value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlockedUser
        {
            get
            {
                return _BlockedUser;
            }
            set
            {
                OnBlockedUserChanging(value);
                ReportPropertyChanging("BlockedUser");
                _BlockedUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BlockedUser");
                OnBlockedUserChanged();
            }
        }
        private global::System.Int32 _BlockedUser;
        partial void OnBlockedUserChanging(global::System.Int32 value);
        partial void OnBlockedUserChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TwitterOnVaadinModel", "FK_BlockedList_User", "User")]
        public User User1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_BlockedList_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_BlockedList_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> User1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_BlockedList_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("TwitterOnVaadinModel.FK_BlockedList_User", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TwitterOnVaadinModel", "FK_BlockedList_User1", "User")]
        public User User2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_BlockedList_User1", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_BlockedList_User1", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> User2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_BlockedList_User1", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("TwitterOnVaadinModel.FK_BlockedList_User1", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TwitterOnVaadinModel", Name="FriendList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FriendList : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FriendList object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="friend">Initial value of the Friend property.</param>
        public static FriendList CreateFriendList(global::System.Int32 id, global::System.Int32 user, global::System.Int32 friend)
        {
            FriendList friendList = new FriendList();
            friendList.id = id;
            friendList.User = user;
            friendList.Friend = friend;
            return friendList;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.Int32 _User;
        partial void OnUserChanging(global::System.Int32 value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Friend
        {
            get
            {
                return _Friend;
            }
            set
            {
                OnFriendChanging(value);
                ReportPropertyChanging("Friend");
                _Friend = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Friend");
                OnFriendChanged();
            }
        }
        private global::System.Int32 _Friend;
        partial void OnFriendChanging(global::System.Int32 value);
        partial void OnFriendChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TwitterOnVaadinModel", "FK_FriendList_User", "User")]
        public User User1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_FriendList_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_FriendList_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> User1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_FriendList_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("TwitterOnVaadinModel.FK_FriendList_User", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TwitterOnVaadinModel", "FK_FriendList_User1", "User")]
        public User User2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_FriendList_User1", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_FriendList_User1", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> User2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_FriendList_User1", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("TwitterOnVaadinModel.FK_FriendList_User1", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TwitterOnVaadinModel", Name="Post")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Post : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Post object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="post1">Initial value of the Post1 property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="author">Initial value of the Author property.</param>
        public static Post CreatePost(global::System.Int32 id, global::System.String post1, global::System.String date, global::System.Int32 user, global::System.Int32 author)
        {
            Post post = new Post();
            post.id = id;
            post.Post1 = post1;
            post.Date = date;
            post.User = user;
            post.Author = author;
            return post;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Post1
        {
            get
            {
                return _Post1;
            }
            set
            {
                OnPost1Changing(value);
                ReportPropertyChanging("Post1");
                _Post1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Post1");
                OnPost1Changed();
            }
        }
        private global::System.String _Post1;
        partial void OnPost1Changing(global::System.String value);
        partial void OnPost1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.String _Date;
        partial void OnDateChanging(global::System.String value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.Int32 _User;
        partial void OnUserChanging(global::System.Int32 value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.Int32 _Author;
        partial void OnAuthorChanging(global::System.Int32 value);
        partial void OnAuthorChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TwitterOnVaadinModel", "FK_Post_User", "User")]
        public User User1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_Post_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_Post_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> User1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_Post_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("TwitterOnVaadinModel.FK_Post_User", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TwitterOnVaadinModel", "FK_Post_User1", "User")]
        public User User1_1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_Post_User1", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_Post_User1", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> User1_1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("TwitterOnVaadinModel.FK_Post_User1", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("TwitterOnVaadinModel.FK_Post_User1", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TwitterOnVaadinModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="admin">Initial value of the Admin property.</param>
        /// <param name="ban">Initial value of the Ban property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String username, global::System.String password, global::System.Boolean admin, global::System.Boolean ban)
        {
            User user = new User();
            user.id = id;
            user.Username = username;
            user.Password = password;
            user.Admin = admin;
            user.Ban = ban;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Forename
        {
            get
            {
                return _Forename;
            }
            set
            {
                OnForenameChanging(value);
                ReportPropertyChanging("Forename");
                _Forename = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Forename");
                OnForenameChanged();
            }
        }
        private global::System.String _Forename;
        partial void OnForenameChanging(global::System.String value);
        partial void OnForenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Surname
        {
            get
            {
                return _Surname;
            }
            set
            {
                OnSurnameChanging(value);
                ReportPropertyChanging("Surname");
                _Surname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Surname");
                OnSurnameChanged();
            }
        }
        private global::System.String _Surname;
        partial void OnSurnameChanging(global::System.String value);
        partial void OnSurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _Age;
        partial void OnAgeChanging(Nullable<global::System.Int32> value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Photo
        {
            get
            {
                return _Photo;
            }
            set
            {
                OnPhotoChanging(value);
                ReportPropertyChanging("Photo");
                _Photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Photo");
                OnPhotoChanged();
            }
        }
        private global::System.String _Photo;
        partial void OnPhotoChanging(global::System.String value);
        partial void OnPhotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Admin
        {
            get
            {
                return _Admin;
            }
            set
            {
                OnAdminChanging(value);
                ReportPropertyChanging("Admin");
                _Admin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Admin");
                OnAdminChanged();
            }
        }
        private global::System.Boolean _Admin;
        partial void OnAdminChanging(global::System.Boolean value);
        partial void OnAdminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ban
        {
            get
            {
                return _Ban;
            }
            set
            {
                OnBanChanging(value);
                ReportPropertyChanging("Ban");
                _Ban = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ban");
                OnBanChanged();
            }
        }
        private global::System.Boolean _Ban;
        partial void OnBanChanging(global::System.Boolean value);
        partial void OnBanChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TwitterOnVaadinModel", "FK_BlockedList_User", "BlockedList")]
        public EntityCollection<BlockedList> BlockedLists
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BlockedList>("TwitterOnVaadinModel.FK_BlockedList_User", "BlockedList");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BlockedList>("TwitterOnVaadinModel.FK_BlockedList_User", "BlockedList", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TwitterOnVaadinModel", "FK_BlockedList_User1", "BlockedList")]
        public EntityCollection<BlockedList> BlockedLists1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BlockedList>("TwitterOnVaadinModel.FK_BlockedList_User1", "BlockedList");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BlockedList>("TwitterOnVaadinModel.FK_BlockedList_User1", "BlockedList", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TwitterOnVaadinModel", "FK_FriendList_User", "FriendList")]
        public EntityCollection<FriendList> FriendLists
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FriendList>("TwitterOnVaadinModel.FK_FriendList_User", "FriendList");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FriendList>("TwitterOnVaadinModel.FK_FriendList_User", "FriendList", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TwitterOnVaadinModel", "FK_FriendList_User1", "FriendList")]
        public EntityCollection<FriendList> FriendLists1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FriendList>("TwitterOnVaadinModel.FK_FriendList_User1", "FriendList");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FriendList>("TwitterOnVaadinModel.FK_FriendList_User1", "FriendList", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TwitterOnVaadinModel", "FK_Post_User", "Post")]
        public EntityCollection<Post> Posts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Post>("TwitterOnVaadinModel.FK_Post_User", "Post");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Post>("TwitterOnVaadinModel.FK_Post_User", "Post", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TwitterOnVaadinModel", "FK_Post_User1", "Post")]
        public EntityCollection<Post> Posts_1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Post>("TwitterOnVaadinModel.FK_Post_User1", "Post");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Post>("TwitterOnVaadinModel.FK_Post_User1", "Post", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
